### ISSUE TITLE
Fix open dependabot alerts

### ISSUE THREAD

**Issue by truedat101** [IoTone/substrate-enterprise-sample-v3#18]
We've got a full set of security fixes recommended, between moderate and severe.  Please review https://github.com/IoTone/substrate-enterprise-sample-v3/security/dependabot

**Comment by Damfortx8** [comment]
the link seems to be broken or I do not have the permissions to see the page
![image](https://user-images.githubusercontent.com/92606981/143245972-f51ba966-6b60-45b8-8295-74e5163ec22b.png)

**Comment by truedat101** [comment]
should be available now.  Please try again.

**Comment by Damfortx8** [comment]
yes, now works, thanks

**Comment by truedat101** [comment]
closing.  Review in a few months.
